---
- name: Check if plist file exists
  stat:
    path: /Library/LaunchDaemons/com.example.gunicorn.plist
  register: plist_file

- name: Load launchd service
  ansible.builtin.command: launchctl load /Library/LaunchDaemons/com.example.gunicorn.plist

- name: Run curl command to check start status
  ansible.builtin.shell:
    cmd: "curl -I -s http://localhost:8000/api/employee/2"
  register: curl_output
  
- name: Print HTTP status code
  ansible.builtin.debug:
    msg: "HTTP Status Code: {{ curl_output.stdout_lines[0] | regex_replace('^HTTP/\\d+\\.\\d+ (\\d+).*$','\\1') }}"