---

- name: Update
  apt:
    update_cache: yes
    upgrade: dist
    state: latest

- name: Clone Git Repository
  git:
    repo: https://github.com/your-username/your-django-app.git
    dest: /path/to/local/folder

- name:  Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    - python3-dev
    - python3-pip
    - python-virtualenv
    - libpq-dev 
    - postgresql 
    - postgresql-contrib
    - curl

- name: Wait for PostgreSQL to be ready
  wait_for:
    host: localhost
    port: 5432
    state: started

- name: Install Django Dependencies
  pip:
    requirements: "{{ role_path }}/files/requirements.txt"


