# Generated by Django 5.0 on 2023-12-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_application', '0002_employee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
