# Generated by Django 5.0 on 2023-12-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_application', '0003_remove_employee_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelephoneNumber',
        ),
    ]
