---
- name: Stop Django Daemon
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Check if plist file exists
      stat:
        path: /Library/LaunchDaemons/com.example.gunicorn.plist
      register: plist_file
  
    - name: Unload launchd service
      ansible.builtin.command: launchctl unload /Library/LaunchDaemons/com.example.gunicorn.plist
      
    - name: Check if the service process is running
      ansible.builtin.shell:
        cmd: "pgrep -f '/opt/homebrew/bin/gunicorn.*web_app.wsgi:application'"
      register: process_check
      ignore_errors: true  # Ignore errors to proceed to the next task

    - name: Print success if service is not running
      ansible.builtin.debug:
        msg: "Service is successfully stopped. No matching process found."
      when: "process_check.rc != 0"

    - name: Print failure if service is still running
      ansible.builtin.debug:
        msg: "Service is still running. Process ID: {{ process_check.stdout | default('N/A') }}"
      when: "process_check.rc == 0"


# - name: Stop Django Daemon
#   hosts: localhost
#   become: true
#   gather_facts: false
#   tasks:
#     - name: Stop Django Daemon Launch Agent
#       community.general.launchd:
#         name: com.example.gunicorn.plist
#         state: stopped

#     - name: Unload Django Daemon Launch Agent
#       community.general.launchd:
#         name: com.example.gunicorn.plist
#         state: unloaded